config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: "homes#top"
  resources :users,only:[:show,:index,:edit,:update]
  resources :tourists do
    resources :comments, only:[:create,:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :tourist

end

app/models/tourist.rb
class Tourist < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tourists,dependent: :destroy
  has_many :comments,dependent: :destroy
  attachment :pofile_image
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
       tourists_path
   end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    tourist=Tourist.find(params[:tourist_id])
    comment=current_user.comments.new(comment_params)
    comment.tourist_id=tourist.id
    comment.save
    redirect_to tourist_path(tourist)
  end

  def destroy
    Comment.find_by(id:params[:id],tourist_id:params[:tourist_id]).destroy
    redirect_to tourist_path(params[:tourist_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/tourists_controller.rb
class TouristsController < ApplicationController
  def new
    @tourist=Tourist.new
  end

  def show
    @tourist=Tourist.find(params[:id])
    @user=@tourist.user
    @comment=Comment.new
  end

  def index
    @user=current_user
    @tourists=Tourist.all
  end

  def create
    @tourist=Tourist.new(tourist_params)
    @tourist.user_id=current_user.id
    if @tourist.save
      redirect_to tourist_path(@tourist.id)
    else
      render "new"
    end
  end

  private
  def tourist_params
    params.require(:tourist).permit(:title,:prace,:impression,:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
    @tourists=Tourist.where(user_id: @user.id)
  end

  def index
    @users=User.all
  end

  def edit
    @user=User.find(params[:id])
    if @user == current_user
         render :edit
    else
       redirect_to user_path(current_user)
    end
  end

  def update
     @user=User.find(params[:id])
     @user.update(user_params)
     redirect_to user_path(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tourists_helper.rb
module TouristsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h2>Welcome to "Enjoy the trip !!".</h2>
<p>様々な地域での観光地や名所、行ってよかったところや美味しいごはん屋さんを紹介してみんなと共有しよう！</br>ここで見つけた観光地や名所を参考に旅行を楽しもう！</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enjoythetrip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand p-3" href="/">Enjoy the trip !!</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
         <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
         <% if user_signed_in? %>
        <li class="nav-item">
         <%= link_to  user_path(current_user.id), class: 'nav-list text-light p-3' do %><i class="fas fa-home"></i>Home<%end%>
        </li>
        <li class="nav-item">
        <%= link_to  users_path, class: 'nav-list text-light p-3'  do%><i class="fas fa-users"></i>Users<%end%>
        </li>
        <li class="nav-item">
        <%= link_to tourists_path, class: 'nav-list text-light p-3' do%><i class="fas fa-book-open"></i>Books<%end%>
        </li>
        <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-list text-light p-3' do%><i class="fas fa-sign-out-alt"></i>Logout<%end%>
        </li>
        <% else %>
        <li class="nav-item">
          <a class= "nav-list text-light p-3" href="/"><i class="fas fa-home"></i>Home</a>
        </li>
      <li class="nav-item">
        <%= link_to  new_user_registration_path, class: 'nav-list text-light p-3' do %><i class="fas fa-user-plus"></i>sign up<%end%>
        </li>
        <li class="nav-item">
        <%= link_to  new_user_session_path, class: 'nav-list text-light p-3' do%><i class="fas fa-sign-in-alt"></i>login<%end%>
        </li>
        <% end %>
      </ul>
      </div>
      </div>
      </nav>
    </header>
    <main>
    <%= yield %>
    </main>
    <footer>

    </footer>
  </body>
</html>

app/views/tourists/index.html.erb
<div class="container">
 <div class="row">
   <div class="col-md-3">
    <%= render 'users/userinfo',user: @user %>
    <div>
    <%= link_to  "Contribute", new_tourist_path, class: "btn btn-secondary" %>
    </div>
   </div>
   <div class="col-md-9">
    <table>
      <thead>
       <tr>
        <th>user</th>
        <th></th>
        <th>place info</th>
        <th></th>
        <th></th>
       </tr>
      </thead>
      <tbody>
       <% @tourists.each do |tourist|%>
       <tr>

        <td><%= attachment_image_tag tourist.user, :pofile_image, :fill,50,50,fallback: "no_image.jpg" %></td>
        <td><%= link_to user_path(tourist.user) do%><%= tourist.user.name %><%end%></td>


        <td><%=link_to tourist_path(tourist.id) do%><%= tourist.title %><%end%></td>
        <td><%= tourist.prace %></td>

       </tr>
       <%end%>
      </tbody>
    </table>
   </div>
 </div>
</div>

app/views/tourists/new.html.erb
<div class="newlist">


<h3>Let's introduce the best place!</h3>
<%= form_with model: @tourist, local:true do |f| %>
<h4>Location Name</h4>
<%= f.text_field :title %>
<h4>Address</h4>
<%= f.text_field :prace %>
<h4>Impression</h4>
<%= f.text_area :impression %>
<h4>Image</h4>
<%= f.attachment_field :image %>

<%= f.submit 'Up'%>

<%end%>


</div>

app/views/tourists/show.html.erb
<div class="container">
    <div class="row">
       <div class="col-md-3">
           <%= render 'users/userinfo',user: @user %>
       </div>
       <div class="col-md-9 show">
           <h2>Tourist Show</h2>
           <table>
               <tbody>
                   <tr>
                    <%= attachment_image_tag @tourist, :image,:fill,500,500, fallback:"no_image.jpg" %>
                   </tr>
                   <tr>
                     <th>Location Name</th>
                     <td><%= @tourist.title %></td>
                   </tr>
                   <tr>
                     <th>Address</th>
                     <td><%= @tourist.prace %></td>
                   </tr>
                   <tr>
                     <th>Impression</th>
                     <td><%= @tourist.impression %></td>
                   </tr>
                   <tr>
                       <th><p>Comments <%= @tourist.comments.count %>件</p></th>
                       <td>
                           <% @tourist.comments.each do |comment| %>
                           <%= link_to user_path(comment.user) do %>
                           <%= attachment_image_tag comment.user, :pofile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                           <%= comment.user.name %>
                           <%end%>
                           <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %>
                           <% if comment.user == current_user %>
                           <%= link_to "Destroy", tourist_comment_path(comment.tourist,comment), method: :delete,class: 'btn btn-danger' %>
                           <%end%>
                           <%end%>
                       </td>
                   </tr>
               </tbody>
           </table>

           <div class="new-comments">
               <%= form_with(model:[@tourist,@comment],local: true) do |f| %>
               <%= f.text_area :comment, placeholder:"Please a comment here" %>
               <%= f.submit "up" %>
               <%end%>
           </div>

       </div>
    </div>
</div>

app/views/users/_userinfo.html.erb
<% if user==current_user %>
<h2>My Info</h2>
<% else%>
<h2>User Info</h2>
<%end%>

<table class="profile-container table table-striped">
  <thead>
    <tr>
     <%= attachment_image_tag user, :pofile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Name</th>
      <th class="profile-name"><%= user.name %></th>
    </tr>
    <tr>
      <th>Introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <% if user == current_user %>


      <th class="btn btn-light w-100"><%= link_to  edit_user_path(current_user)  do %><i class="fas fa-user-cog"></i><%end%></th>
      <% else %>
      <th class="btn btn-light w-100"><%= link_to  edit_user_path(user.id) do %><i class="fas fa-user-cog"></i><%end%></th>
      <% end%>
    </tr>
  </tbody>
  </table>

app/views/users/edit.html.erb
<h1>User Info</h1>

<%= form_with model:@user do |f| %>

<p>Name</p>
<%= f.text_field :name %>
<p>Image</p>
<%= f.attachment_field :pofile_image %>
<p>Introduction</p>
<%= f.text_area :introduction %></br>
<%= f.submit "Update User",class:"btn btn-success" %>
<%end%>

app/views/users/show.html.erb
 <%= render 'users/userinfo',user: @user %>
<h2>User Show</h2>
 <table class="table table-user-show">
            <% @tourists.each do |tourist| %>
          <tr>
              <td>
                <%= attachment_image_tag tourist, :image,:fill,50,50, fallback:"no_image.jpg" %>
              </td>
              <td><%=link_to tourist.title, tourist_path(tourist.id) %></td>
              <td><%= tourist.prace %></td>
          </tr>
             <%end%>
  </table>